// <auto-generated />
using System;
using BeerTap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeerTap.Migrations
{
    [DbContext(typeof(BeerTapContext))]
    [Migration("20250522203636_AddTapToTapSession")]
    partial class AddTapToTapSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeerTap.Models.Tap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taps");
                });

            modelBuilder.Entity("BeerTap.Models.TapEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("TapEvents");
                });

            modelBuilder.Entity("BeerTap.Models.TapSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StopTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TapId");

                    b.ToTable("TapSessions");
                });

            modelBuilder.Entity("BeerTap.Models.TapEvent", b =>
                {
                    b.HasOne("BeerTap.Models.TapSession", "TapSession")
                        .WithMany("TapEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TapSession");
                });

            modelBuilder.Entity("BeerTap.Models.TapSession", b =>
                {
                    b.HasOne("BeerTap.Models.Tap", "Tap")
                        .WithMany("TapSessions")
                        .HasForeignKey("TapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tap");
                });

            modelBuilder.Entity("BeerTap.Models.Tap", b =>
                {
                    b.Navigation("TapSessions");
                });

            modelBuilder.Entity("BeerTap.Models.TapSession", b =>
                {
                    b.Navigation("TapEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
