name: Deploy Chatroom Service

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'Chatroom/**'
  workflow_dispatch:

jobs:
  build-deploy-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Publish Chatroom
        run: dotnet publish Chatroom/Chatroom.csproj -c Release -o out

      - name: Deploy Chatroom
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/var/www/ServerProjects/Chatroom/out"

      - name: Restart Chatroom Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart ChatRoom.service
