name: Deploy All ASP.NET Services

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Chatroom
        run: dotnet publish Chatroom/Chatroom.csproj -c Release -o out

      - name: Publish BeerTap
        run: dotnet publish BeerTap/BeerTap.csproj -c Release -o out

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: out

      - name: Deploy Chatroom
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/Chatroom/*"
          target: "/var/www/ServerProjects/Chatroom/out"

      - name: Deploy BeerTap
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/BeerTap/*"
          target: "/var/www/ServerProjects/BeerTap/out"

  run:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Restart Server Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart ChatRoom.service
            sudo systemctl restart BeerTap.service
