name: Deploy All ASP.NET Services

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.commit.outputs.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  build-chatroom:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Chatroom
        run: dotnet publish ChatRoom/ChatRoom.csproj -c Release -o out/ChatRoom

      - name: Upload Chatroom Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chatroom-app
          path: out/ChatRoom

  build-beertap:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish BeerTap
        run: dotnet publish BeerTap/BeerTap.csproj -c Release -o out/BeerTap

      - name: Upload BeerTap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: beertap-app
          path: out/BeerTap

  deploy-chatroom:
    runs-on: ubuntu-latest
    needs: build-chatroom
    steps:
      - name: Download Chatroom Artifact
        uses: actions/download-artifact@v4
        with:
          name: chatroom-app
          path: out

      - name: Deploy Chatroom
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/var/www/ServerProjects/ChatRoom/out"
          # pre: |
          #   mkdir -p /var/www/ServerProjects/ChatRoom/out

      - name: Restart Chatroom Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo systemctl restart ChatRoom.service

  deploy-beertap:
    runs-on: ubuntu-latest
    needs: build-beertap
    steps:
      - name: Download BeerTap Artifact
        uses: actions/download-artifact@v4
        with:
          name: beertap-app
          path: out

      - name: Deploy BeerTap
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/var/www/ServerProjects/BeerTap/out"
          # pre: |
          #   mkdir -p /var/www/ServerProjects/ChatRoom/out

      - name: Restart BeerTap Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo systemctl restart BeerTap.service
